--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Catalyst-Serendipity/Sponge
build-by-default: true
branches:
- main
projects:
  Sponge:
    path: ""
    icon: "assets/sponge.png"
...
